//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//


package net.trevize.openbox.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://openbox.org/3.4/rc}menu"/>
 *           &lt;element ref="{http://openbox.org/3.4/rc}execute"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://openbox.org/3.4/rc}dialog"/>
 *             &lt;element ref="{http://openbox.org/3.4/rc}wrap"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://openbox.org/3.4/rc}startupnotify"/>
 *             &lt;element ref="{http://openbox.org/3.4/rc}command"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://openbox.org/3.4/rc}panels" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://openbox.org/3.4/rc}desktop"/>
 *           &lt;element ref="{http://openbox.org/3.4/rc}edge"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "menu",
    "execute",
    "dialog",
    "wrap",
    "startupnotify",
    "command",
    "panels",
    "desktop",
    "edge"
})
@XmlRootElement(name = "action")
public class Action {

    protected Menu menu;
    protected String execute;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dialog;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String wrap;
    protected Startupnotify startupnotify;
    protected String command;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String panels;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String desktop;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String edge;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;

    /**
     * Gets the value of the menu property.
     * 
     * @return
     *     possible object is
     *     {@link Menu }
     *     
     */
    public Menu getMenu() {
        return menu;
    }

    /**
     * Sets the value of the menu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Menu }
     *     
     */
    public void setMenu(Menu value) {
        this.menu = value;
    }

    /**
     * Gets the value of the execute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecute() {
        return execute;
    }

    /**
     * Sets the value of the execute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecute(String value) {
        this.execute = value;
    }

    /**
     * Gets the value of the dialog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDialog() {
        return dialog;
    }

    /**
     * Sets the value of the dialog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDialog(String value) {
        this.dialog = value;
    }

    /**
     * Gets the value of the wrap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrap() {
        return wrap;
    }

    /**
     * Sets the value of the wrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrap(String value) {
        this.wrap = value;
    }

    /**
     * Gets the value of the startupnotify property.
     * 
     * @return
     *     possible object is
     *     {@link Startupnotify }
     *     
     */
    public Startupnotify getStartupnotify() {
        return startupnotify;
    }

    /**
     * Sets the value of the startupnotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link Startupnotify }
     *     
     */
    public void setStartupnotify(Startupnotify value) {
        this.startupnotify = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommand(String value) {
        this.command = value;
    }

    /**
     * Gets the value of the panels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPanels() {
        return panels;
    }

    /**
     * Sets the value of the panels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPanels(String value) {
        this.panels = value;
    }

    /**
     * Gets the value of the desktop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesktop() {
        return desktop;
    }

    /**
     * Sets the value of the desktop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesktop(String value) {
        this.desktop = value;
    }

    /**
     * Gets the value of the edge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdge() {
        return edge;
    }

    /**
     * Sets the value of the edge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdge(String value) {
        this.edge = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
