//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//


package net.trevize.openbox.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://openbox.org/3.4/rc}position"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}floatingX"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}floatingY"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}noStrut"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}stacking"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}direction"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}autoHide"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}hideDelay"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}showDelay"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}moveButton"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "position",
    "floatingX",
    "floatingY",
    "noStrut",
    "stacking",
    "direction",
    "autoHide",
    "hideDelay",
    "showDelay",
    "moveButton"
})
@XmlRootElement(name = "dock")
public class Dock {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String position;
    @XmlElement(required = true)
    protected BigInteger floatingX;
    @XmlElement(required = true)
    protected BigInteger floatingY;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String noStrut;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String stacking;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String direction;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String autoHide;
    @XmlElement(required = true)
    protected BigInteger hideDelay;
    @XmlElement(required = true)
    protected BigInteger showDelay;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String moveButton;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the floatingX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFloatingX() {
        return floatingX;
    }

    /**
     * Sets the value of the floatingX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFloatingX(BigInteger value) {
        this.floatingX = value;
    }

    /**
     * Gets the value of the floatingY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFloatingY() {
        return floatingY;
    }

    /**
     * Sets the value of the floatingY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFloatingY(BigInteger value) {
        this.floatingY = value;
    }

    /**
     * Gets the value of the noStrut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoStrut() {
        return noStrut;
    }

    /**
     * Sets the value of the noStrut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoStrut(String value) {
        this.noStrut = value;
    }

    /**
     * Gets the value of the stacking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStacking() {
        return stacking;
    }

    /**
     * Sets the value of the stacking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStacking(String value) {
        this.stacking = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the autoHide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoHide() {
        return autoHide;
    }

    /**
     * Sets the value of the autoHide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoHide(String value) {
        this.autoHide = value;
    }

    /**
     * Gets the value of the hideDelay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHideDelay() {
        return hideDelay;
    }

    /**
     * Sets the value of the hideDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHideDelay(BigInteger value) {
        this.hideDelay = value;
    }

    /**
     * Gets the value of the showDelay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShowDelay() {
        return showDelay;
    }

    /**
     * Sets the value of the showDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShowDelay(BigInteger value) {
        this.showDelay = value;
    }

    /**
     * Gets the value of the moveButton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveButton() {
        return moveButton;
    }

    /**
     * Sets the value of the moveButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveButton(String value) {
        this.moveButton = value;
    }

}
