//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//


package net.trevize.openbox.jaxb;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://openbox.org/3.4/rc}hideDelay"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}applicationIcons"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}file"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}manageDesktops"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}middle"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}submenuShowDelay"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "menu")
public class Menu {

    @XmlElementRefs({
        @XmlElementRef(name = "middle", namespace = "http://openbox.org/3.4/rc", type = JAXBElement.class),
        @XmlElementRef(name = "manageDesktops", namespace = "http://openbox.org/3.4/rc", type = JAXBElement.class),
        @XmlElementRef(name = "submenuShowDelay", namespace = "http://openbox.org/3.4/rc", type = JAXBElement.class),
        @XmlElementRef(name = "hideDelay", namespace = "http://openbox.org/3.4/rc", type = JAXBElement.class),
        @XmlElementRef(name = "applicationIcons", namespace = "http://openbox.org/3.4/rc", type = JAXBElement.class),
        @XmlElementRef(name = "file", namespace = "http://openbox.org/3.4/rc", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
