//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//


package net.trevize.openbox.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://openbox.org/3.4/rc}dragThreshold"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}doubleClickTime"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}screenEdgeWarpTime"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}context" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dragThreshold",
    "doubleClickTime",
    "screenEdgeWarpTime",
    "context"
})
@XmlRootElement(name = "mouse")
public class Mouse {

    @XmlElement(required = true)
    protected BigInteger dragThreshold;
    @XmlElement(required = true)
    protected BigInteger doubleClickTime;
    @XmlElement(required = true)
    protected BigInteger screenEdgeWarpTime;
    @XmlElement(required = true)
    protected List<Context> context;

    /**
     * Gets the value of the dragThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDragThreshold() {
        return dragThreshold;
    }

    /**
     * Sets the value of the dragThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDragThreshold(BigInteger value) {
        this.dragThreshold = value;
    }

    /**
     * Gets the value of the doubleClickTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDoubleClickTime() {
        return doubleClickTime;
    }

    /**
     * Sets the value of the doubleClickTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDoubleClickTime(BigInteger value) {
        this.doubleClickTime = value;
    }

    /**
     * Gets the value of the screenEdgeWarpTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScreenEdgeWarpTime() {
        return screenEdgeWarpTime;
    }

    /**
     * Sets the value of the screenEdgeWarpTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScreenEdgeWarpTime(BigInteger value) {
        this.screenEdgeWarpTime = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the context property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Context }
     * 
     * 
     */
    public List<Context> getContext() {
        if (context == null) {
            context = new ArrayList<Context>();
        }
        return this.context;
    }

}
