//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//


package net.trevize.openbox.jaxb;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.trevize.openbox.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AnimateIconify_QNAME = new QName("http://openbox.org/3.4/rc", "animateIconify");
    private final static QName _PopupShow_QNAME = new QName("http://openbox.org/3.4/rc", "popupShow");
    private final static QName _Direction_QNAME = new QName("http://openbox.org/3.4/rc", "direction");
    private final static QName _MoveButton_QNAME = new QName("http://openbox.org/3.4/rc", "moveButton");
    private final static QName _HideDelay_QNAME = new QName("http://openbox.org/3.4/rc", "hideDelay");
    private final static QName _Weight_QNAME = new QName("http://openbox.org/3.4/rc", "weight");
    private final static QName _Position_QNAME = new QName("http://openbox.org/3.4/rc", "position");
    private final static QName _ManageDesktops_QNAME = new QName("http://openbox.org/3.4/rc", "manageDesktops");
    private final static QName _PopupPosition_QNAME = new QName("http://openbox.org/3.4/rc", "popupPosition");
    private final static QName _Name_QNAME = new QName("http://openbox.org/3.4/rc", "name");
    private final static QName _Stacking_QNAME = new QName("http://openbox.org/3.4/rc", "stacking");
    private final static QName _Panels_QNAME = new QName("http://openbox.org/3.4/rc", "panels");
    private final static QName _Top_QNAME = new QName("http://openbox.org/3.4/rc", "top");
    private final static QName _Dialog_QNAME = new QName("http://openbox.org/3.4/rc", "dialog");
    private final static QName _Left_QNAME = new QName("http://openbox.org/3.4/rc", "left");
    private final static QName _RaiseOnFocus_QNAME = new QName("http://openbox.org/3.4/rc", "raiseOnFocus");
    private final static QName _Command_QNAME = new QName("http://openbox.org/3.4/rc", "command");
    private final static QName _Strength_QNAME = new QName("http://openbox.org/3.4/rc", "strength");
    private final static QName _Edge_QNAME = new QName("http://openbox.org/3.4/rc", "edge");
    private final static QName _Slant_QNAME = new QName("http://openbox.org/3.4/rc", "slant");
    private final static QName _ApplicationIcons_QNAME = new QName("http://openbox.org/3.4/rc", "applicationIcons");
    private final static QName _DragThreshold_QNAME = new QName("http://openbox.org/3.4/rc", "dragThreshold");
    private final static QName _X_QNAME = new QName("http://openbox.org/3.4/rc", "x");
    private final static QName _Y_QNAME = new QName("http://openbox.org/3.4/rc", "y");
    private final static QName _FocusNew_QNAME = new QName("http://openbox.org/3.4/rc", "focusNew");
    private final static QName _ShowDelay_QNAME = new QName("http://openbox.org/3.4/rc", "showDelay");
    private final static QName _ScreenEdgeWarpTime_QNAME = new QName("http://openbox.org/3.4/rc", "screenEdgeWarpTime");
    private final static QName _KeepBorder_QNAME = new QName("http://openbox.org/3.4/rc", "keepBorder");
    private final static QName _Middle_QNAME = new QName("http://openbox.org/3.4/rc", "middle");
    private final static QName _ScreenEdgeStrength_QNAME = new QName("http://openbox.org/3.4/rc", "screen_edge_strength");
    private final static QName _FocusDelay_QNAME = new QName("http://openbox.org/3.4/rc", "focusDelay");
    private final static QName _Desktop_QNAME = new QName("http://openbox.org/3.4/rc", "desktop");
    private final static QName _FocusLast_QNAME = new QName("http://openbox.org/3.4/rc", "focusLast");
    private final static QName _File_QNAME = new QName("http://openbox.org/3.4/rc", "file");
    private final static QName _Firstdesk_QNAME = new QName("http://openbox.org/3.4/rc", "firstdesk");
    private final static QName _Center_QNAME = new QName("http://openbox.org/3.4/rc", "center");
    private final static QName _FollowMouse_QNAME = new QName("http://openbox.org/3.4/rc", "followMouse");
    private final static QName _Right_QNAME = new QName("http://openbox.org/3.4/rc", "right");
    private final static QName _TitleLayout_QNAME = new QName("http://openbox.org/3.4/rc", "titleLayout");
    private final static QName _AutoHide_QNAME = new QName("http://openbox.org/3.4/rc", "autoHide");
    private final static QName _Monitor_QNAME = new QName("http://openbox.org/3.4/rc", "monitor");
    private final static QName _Execute_QNAME = new QName("http://openbox.org/3.4/rc", "execute");
    private final static QName _Enabled_QNAME = new QName("http://openbox.org/3.4/rc", "enabled");
    private final static QName _Wrap_QNAME = new QName("http://openbox.org/3.4/rc", "wrap");
    private final static QName _Size_QNAME = new QName("http://openbox.org/3.4/rc", "size");
    private final static QName _Number_QNAME = new QName("http://openbox.org/3.4/rc", "number");
    private final static QName _DoubleClickTime_QNAME = new QName("http://openbox.org/3.4/rc", "doubleClickTime");
    private final static QName _UnderMouse_QNAME = new QName("http://openbox.org/3.4/rc", "underMouse");
    private final static QName _SubmenuShowDelay_QNAME = new QName("http://openbox.org/3.4/rc", "submenuShowDelay");
    private final static QName _NoStrut_QNAME = new QName("http://openbox.org/3.4/rc", "noStrut");
    private final static QName _DrawContents_QNAME = new QName("http://openbox.org/3.4/rc", "drawContents");
    private final static QName _Policy_QNAME = new QName("http://openbox.org/3.4/rc", "policy");
    private final static QName _PopupTime_QNAME = new QName("http://openbox.org/3.4/rc", "popupTime");
    private final static QName _FloatingX_QNAME = new QName("http://openbox.org/3.4/rc", "floatingX");
    private final static QName _Bottom_QNAME = new QName("http://openbox.org/3.4/rc", "bottom");
    private final static QName _ChainQuitKey_QNAME = new QName("http://openbox.org/3.4/rc", "chainQuitKey");
    private final static QName _FloatingY_QNAME = new QName("http://openbox.org/3.4/rc", "floatingY");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.trevize.openbox.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Menu }
     * 
     */
    public Menu createMenu() {
        return new Menu();
    }

    /**
     * Create an instance of {@link Desktops }
     * 
     */
    public Desktops createDesktops() {
        return new Desktops();
    }

    /**
     * Create an instance of {@link Margins }
     * 
     */
    public Margins createMargins() {
        return new Margins();
    }

    /**
     * Create an instance of {@link Mouse }
     * 
     */
    public Mouse createMouse() {
        return new Mouse();
    }

    /**
     * Create an instance of {@link Resistance }
     * 
     */
    public Resistance createResistance() {
        return new Resistance();
    }

    /**
     * Create an instance of {@link Names }
     * 
     */
    public Names createNames() {
        return new Names();
    }

    /**
     * Create an instance of {@link Applications }
     * 
     */
    public Applications createApplications() {
        return new Applications();
    }

    /**
     * Create an instance of {@link Theme }
     * 
     */
    public Theme createTheme() {
        return new Theme();
    }

    /**
     * Create an instance of {@link Focus }
     * 
     */
    public Focus createFocus() {
        return new Focus();
    }

    /**
     * Create an instance of {@link Keybind }
     * 
     */
    public Keybind createKeybind() {
        return new Keybind();
    }

    /**
     * Create an instance of {@link Resize }
     * 
     */
    public Resize createResize() {
        return new Resize();
    }

    /**
     * Create an instance of {@link PopupFixedPosition }
     * 
     */
    public PopupFixedPosition createPopupFixedPosition() {
        return new PopupFixedPosition();
    }

    /**
     * Create an instance of {@link Dock }
     * 
     */
    public Dock createDock() {
        return new Dock();
    }

    /**
     * Create an instance of {@link Mousebind }
     * 
     */
    public Mousebind createMousebind() {
        return new Mousebind();
    }

    /**
     * Create an instance of {@link OpenboxConfig }
     * 
     */
    public OpenboxConfig createOpenboxConfig() {
        return new OpenboxConfig();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Placement }
     * 
     */
    public Placement createPlacement() {
        return new Placement();
    }

    /**
     * Create an instance of {@link Keyboard }
     * 
     */
    public Keyboard createKeyboard() {
        return new Keyboard();
    }

    /**
     * Create an instance of {@link Startupnotify }
     * 
     */
    public Startupnotify createStartupnotify() {
        return new Startupnotify();
    }

    /**
     * Create an instance of {@link Font }
     * 
     */
    public Font createFont() {
        return new Font();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "animateIconify")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAnimateIconify(String value) {
        return new JAXBElement<String>(_AnimateIconify_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "popupShow")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPopupShow(String value) {
        return new JAXBElement<String>(_PopupShow_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "direction")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDirection(String value) {
        return new JAXBElement<String>(_Direction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "moveButton")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMoveButton(String value) {
        return new JAXBElement<String>(_MoveButton_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "hideDelay")
    public JAXBElement<BigInteger> createHideDelay(BigInteger value) {
        return new JAXBElement<BigInteger>(_HideDelay_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "weight")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createWeight(String value) {
        return new JAXBElement<String>(_Weight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "position")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPosition(String value) {
        return new JAXBElement<String>(_Position_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "manageDesktops")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createManageDesktops(String value) {
        return new JAXBElement<String>(_ManageDesktops_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "popupPosition")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPopupPosition(String value) {
        return new JAXBElement<String>(_PopupPosition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "stacking")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStacking(String value) {
        return new JAXBElement<String>(_Stacking_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "panels")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPanels(String value) {
        return new JAXBElement<String>(_Panels_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "top")
    public JAXBElement<BigInteger> createTop(BigInteger value) {
        return new JAXBElement<BigInteger>(_Top_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "dialog")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDialog(String value) {
        return new JAXBElement<String>(_Dialog_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "left")
    public JAXBElement<BigInteger> createLeft(BigInteger value) {
        return new JAXBElement<BigInteger>(_Left_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "raiseOnFocus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRaiseOnFocus(String value) {
        return new JAXBElement<String>(_RaiseOnFocus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "command")
    public JAXBElement<String> createCommand(String value) {
        return new JAXBElement<String>(_Command_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "strength")
    public JAXBElement<BigInteger> createStrength(BigInteger value) {
        return new JAXBElement<BigInteger>(_Strength_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "edge")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEdge(String value) {
        return new JAXBElement<String>(_Edge_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "slant")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSlant(String value) {
        return new JAXBElement<String>(_Slant_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "applicationIcons")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createApplicationIcons(String value) {
        return new JAXBElement<String>(_ApplicationIcons_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "dragThreshold")
    public JAXBElement<BigInteger> createDragThreshold(BigInteger value) {
        return new JAXBElement<BigInteger>(_DragThreshold_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "x")
    public JAXBElement<BigInteger> createX(BigInteger value) {
        return new JAXBElement<BigInteger>(_X_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "y")
    public JAXBElement<BigInteger> createY(BigInteger value) {
        return new JAXBElement<BigInteger>(_Y_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "focusNew")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFocusNew(String value) {
        return new JAXBElement<String>(_FocusNew_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "showDelay")
    public JAXBElement<BigInteger> createShowDelay(BigInteger value) {
        return new JAXBElement<BigInteger>(_ShowDelay_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "screenEdgeWarpTime")
    public JAXBElement<BigInteger> createScreenEdgeWarpTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_ScreenEdgeWarpTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "keepBorder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createKeepBorder(String value) {
        return new JAXBElement<String>(_KeepBorder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "middle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMiddle(String value) {
        return new JAXBElement<String>(_Middle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "screen_edge_strength")
    public JAXBElement<BigInteger> createScreenEdgeStrength(BigInteger value) {
        return new JAXBElement<BigInteger>(_ScreenEdgeStrength_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "focusDelay")
    public JAXBElement<BigInteger> createFocusDelay(BigInteger value) {
        return new JAXBElement<BigInteger>(_FocusDelay_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "desktop")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDesktop(String value) {
        return new JAXBElement<String>(_Desktop_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "focusLast")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFocusLast(String value) {
        return new JAXBElement<String>(_FocusLast_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "file")
    public JAXBElement<String> createFile(String value) {
        return new JAXBElement<String>(_File_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "firstdesk")
    public JAXBElement<BigInteger> createFirstdesk(BigInteger value) {
        return new JAXBElement<BigInteger>(_Firstdesk_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "center")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCenter(String value) {
        return new JAXBElement<String>(_Center_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "followMouse")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFollowMouse(String value) {
        return new JAXBElement<String>(_FollowMouse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "right")
    public JAXBElement<BigInteger> createRight(BigInteger value) {
        return new JAXBElement<BigInteger>(_Right_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "titleLayout")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTitleLayout(String value) {
        return new JAXBElement<String>(_TitleLayout_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "autoHide")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAutoHide(String value) {
        return new JAXBElement<String>(_AutoHide_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "monitor")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMonitor(String value) {
        return new JAXBElement<String>(_Monitor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "execute")
    public JAXBElement<String> createExecute(String value) {
        return new JAXBElement<String>(_Execute_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "enabled")
    public JAXBElement<Boolean> createEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_Enabled_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "wrap")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createWrap(String value) {
        return new JAXBElement<String>(_Wrap_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "size")
    public JAXBElement<BigInteger> createSize(BigInteger value) {
        return new JAXBElement<BigInteger>(_Size_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "number")
    public JAXBElement<BigInteger> createNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_Number_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "doubleClickTime")
    public JAXBElement<BigInteger> createDoubleClickTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_DoubleClickTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "underMouse")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUnderMouse(String value) {
        return new JAXBElement<String>(_UnderMouse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "submenuShowDelay")
    public JAXBElement<BigInteger> createSubmenuShowDelay(BigInteger value) {
        return new JAXBElement<BigInteger>(_SubmenuShowDelay_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "noStrut")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNoStrut(String value) {
        return new JAXBElement<String>(_NoStrut_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "drawContents")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDrawContents(String value) {
        return new JAXBElement<String>(_DrawContents_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "policy")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPolicy(String value) {
        return new JAXBElement<String>(_Policy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "popupTime")
    public JAXBElement<BigInteger> createPopupTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_PopupTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "floatingX")
    public JAXBElement<BigInteger> createFloatingX(BigInteger value) {
        return new JAXBElement<BigInteger>(_FloatingX_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "bottom")
    public JAXBElement<BigInteger> createBottom(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bottom_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "chainQuitKey")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createChainQuitKey(String value) {
        return new JAXBElement<String>(_ChainQuitKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openbox.org/3.4/rc", name = "floatingY")
    public JAXBElement<BigInteger> createFloatingY(BigInteger value) {
        return new JAXBElement<BigInteger>(_FloatingY_QNAME, BigInteger.class, null, value);
    }

}
