//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//


package net.trevize.openbox.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://openbox.org/3.4/rc}resistance"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}focus"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}placement"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}theme"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}desktops"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}resize"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}margins"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}dock"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}keyboard"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}mouse"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}menu"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}applications"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resistance",
    "focus",
    "placement",
    "theme",
    "desktops",
    "resize",
    "margins",
    "dock",
    "keyboard",
    "mouse",
    "menu",
    "applications"
})
@XmlRootElement(name = "openbox_config")
public class OpenboxConfig {

    @XmlElement(required = true)
    protected Resistance resistance;
    @XmlElement(required = true)
    protected Focus focus;
    @XmlElement(required = true)
    protected Placement placement;
    @XmlElement(required = true)
    protected Theme theme;
    @XmlElement(required = true)
    protected Desktops desktops;
    @XmlElement(required = true)
    protected Resize resize;
    @XmlElement(required = true)
    protected Margins margins;
    @XmlElement(required = true)
    protected Dock dock;
    @XmlElement(required = true)
    protected Keyboard keyboard;
    @XmlElement(required = true)
    protected Mouse mouse;
    @XmlElement(required = true)
    protected Menu menu;
    @XmlElement(required = true)
    protected Applications applications;

    /**
     * Gets the value of the resistance property.
     * 
     * @return
     *     possible object is
     *     {@link Resistance }
     *     
     */
    public Resistance getResistance() {
        return resistance;
    }

    /**
     * Sets the value of the resistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resistance }
     *     
     */
    public void setResistance(Resistance value) {
        this.resistance = value;
    }

    /**
     * Gets the value of the focus property.
     * 
     * @return
     *     possible object is
     *     {@link Focus }
     *     
     */
    public Focus getFocus() {
        return focus;
    }

    /**
     * Sets the value of the focus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Focus }
     *     
     */
    public void setFocus(Focus value) {
        this.focus = value;
    }

    /**
     * Gets the value of the placement property.
     * 
     * @return
     *     possible object is
     *     {@link Placement }
     *     
     */
    public Placement getPlacement() {
        return placement;
    }

    /**
     * Sets the value of the placement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Placement }
     *     
     */
    public void setPlacement(Placement value) {
        this.placement = value;
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link Theme }
     *     
     */
    public Theme getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link Theme }
     *     
     */
    public void setTheme(Theme value) {
        this.theme = value;
    }

    /**
     * Gets the value of the desktops property.
     * 
     * @return
     *     possible object is
     *     {@link Desktops }
     *     
     */
    public Desktops getDesktops() {
        return desktops;
    }

    /**
     * Sets the value of the desktops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Desktops }
     *     
     */
    public void setDesktops(Desktops value) {
        this.desktops = value;
    }

    /**
     * Gets the value of the resize property.
     * 
     * @return
     *     possible object is
     *     {@link Resize }
     *     
     */
    public Resize getResize() {
        return resize;
    }

    /**
     * Sets the value of the resize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resize }
     *     
     */
    public void setResize(Resize value) {
        this.resize = value;
    }

    /**
     * Gets the value of the margins property.
     * 
     * @return
     *     possible object is
     *     {@link Margins }
     *     
     */
    public Margins getMargins() {
        return margins;
    }

    /**
     * Sets the value of the margins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Margins }
     *     
     */
    public void setMargins(Margins value) {
        this.margins = value;
    }

    /**
     * Gets the value of the dock property.
     * 
     * @return
     *     possible object is
     *     {@link Dock }
     *     
     */
    public Dock getDock() {
        return dock;
    }

    /**
     * Sets the value of the dock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dock }
     *     
     */
    public void setDock(Dock value) {
        this.dock = value;
    }

    /**
     * Gets the value of the keyboard property.
     * 
     * @return
     *     possible object is
     *     {@link Keyboard }
     *     
     */
    public Keyboard getKeyboard() {
        return keyboard;
    }

    /**
     * Sets the value of the keyboard property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keyboard }
     *     
     */
    public void setKeyboard(Keyboard value) {
        this.keyboard = value;
    }

    /**
     * Gets the value of the mouse property.
     * 
     * @return
     *     possible object is
     *     {@link Mouse }
     *     
     */
    public Mouse getMouse() {
        return mouse;
    }

    /**
     * Sets the value of the mouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mouse }
     *     
     */
    public void setMouse(Mouse value) {
        this.mouse = value;
    }

    /**
     * Gets the value of the menu property.
     * 
     * @return
     *     possible object is
     *     {@link Menu }
     *     
     */
    public Menu getMenu() {
        return menu;
    }

    /**
     * Sets the value of the menu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Menu }
     *     
     */
    public void setMenu(Menu value) {
        this.menu = value;
    }

    /**
     * Gets the value of the applications property.
     * 
     * @return
     *     possible object is
     *     {@link Applications }
     *     
     */
    public Applications getApplications() {
        return applications;
    }

    /**
     * Sets the value of the applications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Applications }
     *     
     */
    public void setApplications(Applications value) {
        this.applications = value;
    }

}
