//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://openbox.org/3.4/rc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.trevize.openbox.jaxb;
