//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//


package net.trevize.openbox.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://openbox.org/3.4/rc}drawContents"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}popupShow"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}popupPosition"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}popupFixedPosition"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drawContents",
    "popupShow",
    "popupPosition",
    "popupFixedPosition"
})
@XmlRootElement(name = "resize")
public class Resize {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String drawContents;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String popupShow;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String popupPosition;
    @XmlElement(required = true)
    protected PopupFixedPosition popupFixedPosition;

    /**
     * Gets the value of the drawContents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawContents() {
        return drawContents;
    }

    /**
     * Sets the value of the drawContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawContents(String value) {
        this.drawContents = value;
    }

    /**
     * Gets the value of the popupShow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopupShow() {
        return popupShow;
    }

    /**
     * Sets the value of the popupShow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopupShow(String value) {
        this.popupShow = value;
    }

    /**
     * Gets the value of the popupPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopupPosition() {
        return popupPosition;
    }

    /**
     * Sets the value of the popupPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopupPosition(String value) {
        this.popupPosition = value;
    }

    /**
     * Gets the value of the popupFixedPosition property.
     * 
     * @return
     *     possible object is
     *     {@link PopupFixedPosition }
     *     
     */
    public PopupFixedPosition getPopupFixedPosition() {
        return popupFixedPosition;
    }

    /**
     * Sets the value of the popupFixedPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopupFixedPosition }
     *     
     */
    public void setPopupFixedPosition(PopupFixedPosition value) {
        this.popupFixedPosition = value;
    }

}
