//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 04:42:10 PM CEST 
//


package net.trevize.openbox.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://openbox.org/3.4/rc}name"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}titleLayout"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}keepBorder"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}animateIconify"/>
 *         &lt;element ref="{http://openbox.org/3.4/rc}font" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "titleLayout",
    "keepBorder",
    "animateIconify",
    "font"
})
@XmlRootElement(name = "theme")
public class Theme {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String titleLayout;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String keepBorder;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String animateIconify;
    @XmlElement(required = true)
    protected List<Font> font;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the titleLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleLayout() {
        return titleLayout;
    }

    /**
     * Sets the value of the titleLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleLayout(String value) {
        this.titleLayout = value;
    }

    /**
     * Gets the value of the keepBorder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeepBorder() {
        return keepBorder;
    }

    /**
     * Sets the value of the keepBorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeepBorder(String value) {
        this.keepBorder = value;
    }

    /**
     * Gets the value of the animateIconify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnimateIconify() {
        return animateIconify;
    }

    /**
     * Sets the value of the animateIconify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnimateIconify(String value) {
        this.animateIconify = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the font property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFont().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Font }
     * 
     * 
     */
    public List<Font> getFont() {
        if (font == null) {
            font = new ArrayList<Font>();
        }
        return this.font;
    }

}
